### PR TITLE
Enable license test and fix licensing for python3. Fix #12

### LINKED ISSUE #12: Python3 support
when installed with `pip3 install dmgbuild`, appending the Licence fails in resources.py with usage of `basestring` which is removed in python3

### PR DESCRIPTION
**Pull request by PeterPetrik**
tested with python setup.py test and python3 setup.py test

### CODE REVIEW

**Comment by PeterPetrik** [comment]
@al45tair would it be possible to merge this issue are create new packages? thanks

Fixes #12

**Comment by PeterPetrik** [comment]
@al45tair would it be possible to merge this issue? i am getting pull requests on my fork https://github.com/PeterPetrik/dmgbuild/pull/1 which is very suboptimal.

**Comment by tmontes** [comment]
@al45tair, much like @PeterPetrik (thanks for the PR!), I'm gently nudging you to help merge this.

I've been working on improving [Mu Editor](https://github.com/mu-editor/mu/)'s macOS packaging, collaborating with other projects such as [briefcase](https://github.com/beeware/briefcase/), and successfully tested this PR.

I'll gladly help out in making this happen. Thanks again for dmgbuild. :)

**Comment by tmontes** [comment]
@al45tair, thanks a lot for merging this and for releasing an updated `dmgbuild` package. I confirm I've just tested it successfully for Mu's packaging purposes. :)

**Pull request merged**
